title: "Carlos Reyes"
description: "Reflexiones, medicina, filosof√≠a y disciplina."
theme: minima
header_pages:
  - about.md
  - medicina.md
  - filosofia.md
  - fe-y-etica.md
  - proyectos-personales.md
